name: bacayuk
version: 1.0.0+1
publish_to: none
description: Project Aplikasi Perpustakaan Digital.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  another_flutter_splash_screen: ^1.2.0
  lottie: ^3.0.0
  flutter_onboarding_slider: ^1.0.11
  dio: 5.4.0
  curved_navigation_bar: ^1.0.3
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  image_picker: ^1.0.7
  flutter_launcher_icons: ^0.13.1
  quickalert: ^1.0.2
  auto_size_text: ^3.0.0
  top_snackbar_flutter: ^3.1.0
  connectivity_plus: ^5.0.2
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  permission_handler: ^11.3.0
  jwt_decoder: ^2.0.1
  device_info_plus: ^9.1.2
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  syncfusion_flutter_pdfviewer: ^24.2.8
  file_picker: ^8.0.1
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - asset/image/
    - asset/json/
  fonts:
    - family: Poppins
      fonts:
        - asset: asset/fonts/poppins/Poppins-Regular.ttf
    - family: Signika
      fonts:
        - asset: asset/fonts/signika/Signika-Regular.ttf
  uses-material-design: true

flutter_launcher_icons:
  android: launcher_icon
  image_path: asset/image/bacayuk_lg.png
  ios: true
